INBOX_NAMESPACE_NAME = "Inbox"
INBOX_NAMESPACE_KIND = "inbox"

TRASH_NAMESPACE_NAME = "Trash"
TRASH_NAMESPACE_KIND = "trash"

VAULT_ROOT_NAMESPACE_NAME = "Vault"
VAULT_ROOT_NAMESPACE_KIND = "vault_root"

REGULAR_NAMESPACE_KIND = "regular"
